### ISSUE TITLE
Incorrect index for events fired when using chart.setTimeline(true)

### ISSUE THREAD

**Issue by piemmm** [vaadin/vaadin-charts-flow#257]
Hello!

A bug with vaadin line charts with 50K+ of point values in:

```
chart = new Chart(ChartType.LINE);
chart.setTimeline(true);
chart.addPointMouseOverListener(e->mouseOverFired(e));
(...then load 50K points of data into a series, or multiple series)
```

```
public void mouseOverFired(PointMouseOverEvent e) {
   e.getItemIndex()  and e.getItem() are incorrect for the point hovered over in the graph - 
   I will hover over what should be point 40,000 and will instead get an index returned of 
   about 1300 (depending on graph size)
}
```

The issue appears to be with the reduction of datapoints that I suspect setTimeline(true) causes to happen.  The chart will only show a max index of about 1500 points (fullscreen in my browser) so I think there's some form of reducing going on given the dataset size

If I pass < 1500 points to the linechart, everything works swimmingly. So it looks like the event index isn't taking into account the reduction method being used

**Comment by piemmm** [comment]
Hi, thankyou for the swift response!

Yes, that does temporarily workaround the issue (though the GUI is noticeably slower as a result)

So it appears that if datagrouping is enabled, the indexes that are fired off are incorrect

**Comment by alvarezguille** [comment]
If datagrouping is enabled the indexes won't be reliable because they refer to points that are not from the original data, the data points in the client refer to ranges with grouped value that can be sum or average depending on chart type and server is not aware of that and at the moment it's a limitation.
We should document better this behavior.
It might make sense to create an enhancement request to provide info about the range of the datagroup of the point involved in the event.

**Comment by alvarezguille** [comment]
One thing I forgot to ask, what are you trying to achieve by adding a server-side MouseOver listener to a chart with 50k points?

**Comment by alvarezguille** [comment]
>It seemed proper to get a system.out of the actual index that way for the example in this ticket
Ok, makes sense to verify the issue, but otherwise it's probably a bad idea.
If this limitation is affecting your use case and you can't disable data grouping please create a new enhancement request to provide info about the range of the datagroup of the point involved in the event

>It would be good to document this, as it's not expected behaviour for the chart to suddenly return wrong indexes with this option enabled
I agree it's unexpected and created a new issue for the docs improvements in #258

>(btw, cloudflare is reporting your website is down yet again)
Team is working on it at the moment, sorry for the inconvenience
