### ISSUE TITLE
Chart doesn't display when I use makeCustomized on DataSeriesItem

### ISSUE THREAD

**Issue by ElZorrito** [vaadin/vaadin-charts-flow#272]
Chart doesn't display when I use makeCustomized on DataSeriesItem (v6.2.2):
- on custom DataSeriesItem when I call makeCustomized
- on FlagItem who call makeCustomized
- on DataSeriesItem when I call setName (who call makeCustomized )

**Comment by alvarezguille** [comment]
Thanks for reporting this @ElZorrito 

How many data series item does the chart have?

Do you get any exception on server or browser console? If not, can you provide a simple example that reproduces this issue?

**Comment by ElZorrito** [comment]
Thanks for your reply.
I have more than 3000 data series item and no error on console or browser console.
I make some tests, that's my code :
`public class CustomDataSeriesItem extends DataSeriesItem {

	private String customField;
	
	public CustomDataSeriesItem() {
		super();
		makeCustomized();
	}

	public String getCustomField() {
		return customField;
	}

	public void setCustomField(String customField) {
		this.customField = customField;
	}
}`
and to draw the chart :
`Chart testChart = new Chart();
Configuration config = testChart.getConfiguration();
DataSeries series = new DataSeries();
series.setName("Test");
int maxDatas = 2001;
for (int i = 0;i<maxDatas;i++) {
	CustomDataSeriesItem item = new CustomDataSeriesItem();
	item.setX(i);
	item.setY(1);
	series.add(item);
	i++;
}
config.setSeries(series);
testChart.drawChart(true);`

This sample doesn't work. But, if I put maxDatas to 2000, chart will display..
So over than 2000, chart won't display.

**Comment by alvarezguille** [comment]
My current guess is that some optimization in the underlying library is happening, if that's the case browser console should be showing something like:
>Highcharts error #12: www.highcharts.com/errors/12

And it should be fixed by setting `turboThreshold` to 0 or a number higher than your series size. You can do this with [setTurboThreshold api in PlotOptions](https://vaadin.com/api/com.vaadin/vaadin-charts-flow/6.3.0/com/vaadin/flow/component/charts/model/PlotOptionsSeries.html#setTurboThreshold-java.lang.Number-)

Can you check if that helps?

**Comment by ElZorrito** [comment]
It works!!
Thank you very much for the quick help.
And sorry for the issue, it is not.

**Comment by alvarezguille** [comment]
Great that it worked! I'll close the issue
